name: 💡 Features and Idea request
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels:
  - Idea

body:
  - type: textarea
    id: idea-request
    attributes:
      label: Idea Request
      description: 기능 확장 또는 현재 모듈의 변경, 피쳐 엔지니어링에 대한 아이디어를 적어주세요.
      placeholder: "자세한 설명을 적어주세요."
    validations:
      required: true
